<template>
<div>
    <div class="header shadow-md w-screen bg-white">
        <header-frame page="usecondition"></header-frame>
    </div>

    <div class="flex flex-col ml-10 my-5 sm:ml-40 sm:my-10">
        <div class="block text-black text-2xl sm:text-4xl font-semibold my-8 leading-relaxed">
            Conditions d’utilisation
        </div>
        <div class="text-xl sm:text-sm text-black text-left leading-relaxed w-5/6 sm:w-4/5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate mi sit amet mauris commodo quis imperdiet. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Ac tortor vitae purus faucibus ornare suspendisse sed. Ut morbi tincidunt augue interdum. Ultrices tincidunt arcu non sodales. Tristique senectus et netus et malesuada fames ac turpis. Sit amet risus nullam eget felis eget nunc lobortis. Eget nullam non nisi est. Quis commodo odio aenean sed adipiscing diam. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Sit amet commodo nulla facilisi nullam vehicula ipsum. Viverra mauris in aliquam sem fringilla ut morbi. Congue quisque egestas diam in. Justo laoreet sit amet cursus. Aliquet eget sit amet tellus cras adipiscing enim eu. Vel orci porta non pulvinar neque laoreet suspendisse interdum.
            <br><br>
            Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Euismod in pellentesque massa placerat duis ultricies lacus. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Vel turpis nunc eget lorem dolor sed. Vitae congue mauris rhoncus aenean. Mattis molestie a iaculis at erat. Velit egestas dui id ornare arcu odio ut sem nulla. Nullam ac tortor vitae purus. Fermentum et sollicitudin ac orci phasellus egestas. At erat pellentesque adipiscing commodo elit at imperdiet dui. Senectus et netus et malesuada fames ac turpis egestas sed.
            <br><br>
            Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Felis donec et odio pellentesque diam volutpat commodo. Fringilla urna porttitor rhoncus dolor purus non enim. Sit amet luctus venenatis lectus magna fringilla. Quis lectus nulla at volutpat diam ut venenatis tellus. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Vitae congue eu consequat ac felis donec et odio pellentesque. Ac placerat vestibulum lectus mauris ultrices eros in. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ultrices sagittis orci a scelerisque purus semper eget duis at. Interdum velit laoreet id donec ultrices tincidunt. Eu scelerisque felis imperdiet proin fermentum leo. Massa enim nec dui nunc mattis. Enim sed faucibus turpis in. Mauris pharetra et ultrices neque ornare aenean. Duis ut diam quam nulla porttitor massa id. Mauris ultrices eros in cursus. Nullam non nisi est sit amet facilisis magna etiam.
            <br><br>
            Tellus orci ac auctor augue mauris augue neque. Convallis posuere morbi leo urna molestie at elementum. Mi eget mauris pharetra et ultrices neque ornare. Rutrum quisque non tellus orci ac auctor. Mi eget mauris pharetra et ultrices. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Nisi porta lorem mollis aliquam ut porttitor. Id semper risus in hendrerit. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. At tellus at urna condimentum mattis pellentesque id. Non pulvinar neque laoreet suspendisse interdum consectetur. Diam quam nulla porttitor massa. Faucibus nisl tincidunt eget nullam non nisi est sit.
            <br><br>
            Iaculis urna id volutpat lacus laoreet. Ipsum faucibus vitae aliquet nec ullamcorper. Donec ac odio tempor orci. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Praesent tristique magna sit amet purus gravida. Cras sed felis eget velit aliquet sagittis. Velit ut tortor pretium viverra. Praesent semper feugiat nibh sed pulvinar. In arcu cursus euismod quis viverra nibh. Non enim praesent elementum facilisis leo. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Ante in nibh mauris cursus mattis molestie a iaculis at. Viverra ipsum nunc aliquet bibendum enim. A lacus vestibulum sed arcu non odio. Id neque aliquam vestibulum morbi. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique.
            <br><br>
            In egestas erat imperdiet sed euismod nisi porta lorem mollis. Tortor dignissim convallis aenean et. Quis hendrerit dolor magna eget est lorem ipsum dolor. Neque volutpat ac tincidunt vitae. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Lacus laoreet non curabitur gravida arcu ac tortor. Sit amet volutpat consequat mauris nunc. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Tempor orci eu lobortis elementum nibh tellus molestie. Aliquam vestibulum morbi blandit cursus risus at ultrices. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Nibh sed pulvinar proin gravida hendrerit lectus. Et egestas quis ipsum suspendisse ultrices. Diam sollicitudin tempor id eu nisl nunc mi ipsum.
            <br><br>
            Ultricies leo integer malesuada nunc vel risus commodo viverra. Tellus integer feugiat scelerisque varius morbi enim nunc. Porta nibh venenatis cras sed felis. Turpis egestas pretium aenean pharetra magna. Nunc eget lorem dolor sed viverra ipsum nunc. Id velit ut tortor pretium viverra suspendisse. Velit laoreet id donec ultrices tincidunt arcu non. Tristique senectus et netus et malesuada fames ac. Integer eget aliquet nibh praesent tristique magna sit amet purus. Aenean sed adipiscing diam donec adipiscing tristique.
            <br><br>
            Condimentum vitae sapien pellentesque habitant morbi. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Pretium viverra suspendisse potenti nullam ac tortor vitae. Habitant morbi tristique senectus et netus. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Pretium nibh ipsum consequat nisl vel. Mauris nunc congue nisi vitae. Velit ut tortor pretium viverra suspendisse potenti. Tortor consequat id porta nibh. Quam vulputate dignissim suspendisse in.
            <br><br>
            Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Sed sed risus pretium quam vulputate. Faucibus pulvinar elementum integer enim. Scelerisque mauris pellentesque pulvinar pellentesque. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. At in tellus integer feugiat. Pretium lectus quam id leo in vitae turpis massa sed. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Sem integer vitae justo eget magna fermentum iaculis. Sapien et ligula ullamcorper malesuada proin libero nunc. Nam aliquam sem et tortor consequat. Augue ut lectus arcu bibendum at varius vel pharetra vel. Eu mi bibendum neque egestas. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Sit amet tellus cras adipiscing enim eu turpis.
            <br><br>
            Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Pharetra vel turpis nunc eget lorem dolor. In vitae turpis massa sed elementum tempus egestas sed sed. Pharetra diam sit amet nisl suscipit adipiscing. Justo laoreet sit amet cursus sit amet dictum sit amet. Ultricies mi eget mauris pharetra. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Nec nam aliquam sem et. Cras sed felis eget velit aliquet sagittis id consectetur. Duis ut diam quam nulla porttitor massa. Non arcu risus quis varius quam quisque id. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Vitae ultricies leo integer malesuada nunc vel risus. In nisl nisi scelerisque eu ultrices. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Congue mauris rhoncus aenean vel elit scelerisque mauris. Eu lobortis elementum nibh tellus molestie nunc non. Donec et odio pellentesque diam volutpat commodo.
            <br><br>
            Pellentesque habitant morbi tristique senectus et. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Duis ut diam quam nulla porttitor massa id. Eu non diam phasellus vestibulum lorem. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Consectetur adipiscing elit duis tristique. In egestas erat imperdiet sed. Justo nec ultrices dui sapien eget mi. Elementum curabitur vitae nunc sed velit dignissim. Donec et odio pellentesque diam volutpat commodo sed. At consectetur lorem donec massa sapien. Volutpat ac tincidunt vitae semper quis. At varius vel pharetra vel. Volutpat ac tincidunt vitae semper quis. Gravida neque convallis a cras semper auctor neque vitae. Odio pellentesque diam volutpat commodo sed. Sagittis vitae et leo duis ut diam quam nulla porttitor.
            <br><br>
            Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Feugiat scelerisque varius morbi enim nunc. Scelerisque fermentum dui faucibus in ornare quam viverra. Elit pellentesque habitant morbi tristique senectus et netus. Amet purus gravida quis blandit turpis cursus in. Nulla facilisi nullam vehicula ipsum a. At quis risus sed vulputate odio. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. In massa tempor nec feugiat nisl. Lacus sed turpis tincidunt id aliquet risus feugiat. At ultrices mi tempus imperdiet. Volutpat consequat mauris nunc congue nisi vitae. Faucibus turpis in eu mi bibendum neque egestas. Scelerisque purus semper eget duis. Porttitor eget dolor morbi non arcu. Sit amet commodo nulla facilisi. At volutpat diam ut venenatis. Tincidunt arcu non sodales neque sodales ut etiam sit amet.
            <br><br>
            Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Mauris rhoncus aenean vel elit scelerisque. Ullamcorper malesuada proin libero nunc consequat. Vitae justo eget magna fermentum iaculis eu non. Sed egestas egestas fringilla phasellus faucibus scelerisque. Tristique nulla aliquet enim tortor at auctor. Rhoncus dolor purus non enim praesent. Suscipit adipiscing bibendum est ultricies. A arcu cursus vitae congue mauris rhoncus aenean vel. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Vel eros donec ac odio. Scelerisque in dictum non consectetur a erat. Risus sed vulputate odio ut enim blandit volutpat. At ultrices mi tempus imperdiet nulla malesuada. Mauris cursus mattis molestie a iaculis at erat pellentesque.
            <br><br>
            Quis ipsum suspendisse ultrices gravida. Massa sed elementum tempus egestas sed sed risus. Hac habitasse platea dictumst quisque sagittis purus sit. Consectetur libero id faucibus nisl tincidunt eget nullam non. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Habitant morbi tristique senectus et netus et. Ipsum dolor sit amet consectetur adipiscing elit ut. Id venenatis a condimentum vitae sapien pellentesque habitant. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Pulvinar pellentesque habitant morbi tristique senectus. Volutpat commodo sed egestas egestas fringilla phasellus. Habitant morbi tristique senectus et netus et malesuada fames. Elementum nisi quis eleifend quam adipiscing vitae proin. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Mattis nunc sed blandit libero volutpat sed cras. Id nibh tortor id aliquet lectus proin. Odio pellentesque diam volutpat commodo. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sit amet massa vitae tortor condimentum lacinia quis vel eros.
        </div>
    </div>

    <footer-frame></footer-frame>
</div>
</template>

<script>
import HeaderFrame from '../../components/helper/header-frame.vue'
import FooterFrame from '../../components/helper/footer-frame.vue'
export default {
  name: 'index',
  components: { HeaderFrame, FooterFrame }
}
</script>
