/* eslint-disable */
require('./ic_arsen_2')
require('./ic_arsen-logo-green')
require('./ic_arsen-logo-white')
require('./ic_arsen')
require('./ic_caisse')
require('./ic_fleche')
require('./ic_fusee')
require('./ic_globe')
require('./ic_horloge')
require('./ic_inf')
require('./ic_menu')
require('./ic_pin')
require('./ic_seringue')
require('./ic_sup')
require('./ic_valide')
require('./icon_logo')
